# SellGUI - Konfigurációs fájl

settings:
  # Hangok listája: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sell-sound: "ENTITY_PLAYER_LEVELUP"
  fail-sound: "ENTITY_VILLAGER_NO"
  # Melyik slotban legyen az eladó gomb az első sorban (0-8 között)
  button-slot: 4

messages:
  no-permission: "&7[&2SellGUI&7] &cNincs jogosultságod ehhez a művelethez!"
  sell-success: "&7[&2SellGUI&7] &aSikeresen eladtál mindent &f%price% $ &aértékben!"
  title: "&6+ %price% $"
  subtitle: "&7Az összeg jóváírva!"
  item-added: "&7[&2SellGUI&7] &aTárgy rögzítve az adatbázisba! Ár: &e%price% $"

# Az eladó gomb kinézete (Alapértelmezett, ha még nem állítottad be játékon belül)
button-item:
  ==: org.bukkit.inventory.ItemStack
  v: 3955
  type: LIME_STAINED_GLASS_PANE
  meta:
    ==: ItemMeta
    display-name: '{"text":"§a§lELADÁS INDÍTÁSA"}'
    lore:
    - '{"text":"§7Kattints ide a bent lévő"}'
    - '{"text":"§7tárgyak eladásához!"}'

# Az árak listája ide fog kerülni automatikusan a /selladmin add használatakor
prices: {}
