gui-settings:
  title: "&2&lEladás"
  button-name: "&a&lELADÁS INDÍTÁSA"
  button-lore:
    - "&7Kattints ide a bent lévő"
    - "&7tárgyak eladásához!"

multipliers:
  bronze: 1.25
  silver: 1.5
  gold: 1.75

messages:
  prefix: "&7[&2SellGUI&7] "
  no-item: "&cNincs eladható tárgy a felületen!"
  sell-success: "&aSikeres eladás: &f%amount%$"
  no-permission: "&cNincs jogod ehhez!"
  admin-add: "&aTárgy rögzítve: &f%item% &7- &e%price%$"
  database-wipe: "&cMinden elmentett ár törölve lett!"
