gui-settings:
  title: "&#4eccf3&lEladó Felület"
  button-name: "&#55ff55&lELADÁS INDÍTÁSA"
  button-lore:
    - "&7Kattints ide az eladáshoz!"

multipliers:
  bronze: 1.25
  silver: 1.5
  gold: 1.75

messages:
  prefix: "&7[&#fffa00Eladás&7] "
  no-item: "&#F12727Nincs eladható tárgy a felületen!"
  # Változók: %amount%, %multiplier%
  sell-success: "&#00FF3BSikeres eladást végeztél el &n%amount%&#00FF3B értékben! &7(%multiplier)"
  sell-title-sub: "&7Szorzó: &e%multiplier%x"
  no-permission: "&cNincs jogod ehhez!"
  admin-add: "&aTárgy rögzítve: &f%item% &7- &e%price%$"
  database-wipe: "&cMinden elmentett ár törölve lett!"
